name: Deploy Website
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # هاد السطر هو اللي بحل المشكلة وبجبره يستخدم Node 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        [cite_start]uses: actions/checkout@v4 [cite: 68-69]
      - name: Deploy to GitHub Pages
        [cite_start]uses: peaceiris/actions-gh-pages@v4 [cite: 70-71]
        with:
          [cite_start]github_token: ${{ secrets.GITHUB_TOKEN }} [cite: 73]
          [cite_start]publish_dir: ./ [cite: 73]